// <auto-generated />
using Conta.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Conta.DAL.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20180819013600_conta")]
    partial class conta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Conta.DAL.Entidades.ContaDAO", b =>
                {
                    b.Property<long>("ID_Conta")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<decimal>("Valor");

                    b.HasKey("ID_Conta");

                    b.ToTable("Conta");
                });

            modelBuilder.Entity("Conta.DAL.Entidades.OperacaoDAO", b =>
                {
                    b.Property<long>("ID_Operacao")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ContaID_Conta");

                    b.Property<string>("Tipo_Operacao");

                    b.Property<decimal>("Valor");

                    b.HasKey("ID_Operacao");

                    b.HasIndex("ContaID_Conta");

                    b.ToTable("Operacao");
                });

            modelBuilder.Entity("Conta.DAL.Entidades.OperacaoDAO", b =>
                {
                    b.HasOne("Conta.DAL.Entidades.ContaDAO", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaID_Conta");
                });
#pragma warning restore 612, 618
        }
    }
}
